### ISSUE TITLE
Warning: Missing argument 1 for BlogPlugin::onMenu() in /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/plugins/Blog/BlogPlugin.php on line 47

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/BootWiki#1]
**Warning: Missing argument 1 for BlogPlugin::onMenu() in /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/plugins/Blog/BlogPlugin.php on line 47**

Tested on OVH, php 5.6 and 7.2 

BlogPlugin.php
```
	public function onMenu(&$menu){ //line 47
		//Add links to menu(Or customize current menu):
		//Example:
		//$menu["Title"] = "link" (page path relative to 'applications' folder, or a full link: 'https://example.com')
		$menu["Dir Blog"] = "example/";
		return true;
	}
```

**Comment by simon511000** [comment]
Error in php 7.2 : 
**Fatal error: Uncaught ArgumentCountError: Too few arguments to function BlogPlugin::onMenu(), 0 passed in /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/Events.php on line 49 and exactly 1 expected in /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/plugins/Blog/BlogPlugin.php:47 Stack trace: #0 /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/Events.php(49): BlogPlugin->onMenu() #1 /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/index.php(135): Event::handle('Menu') #2 /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/index.php(63): body() #3 {main} thrown in /home/simonfrjdh/autre/kod/data/User/admin/home/desktop/BootWiki-master/plugins/Blog/BlogPlugin.php on line 47**

**Comment by mitchellurgero** [comment]
I'll have to look at this another day.

**Comment by simon511000** [comment]
Ok thanks ;)

**Comment by simon511000** [comment]
I've found the solution : 
`public function onMenu(&$menu = array()){`
and it's work
